### ISSUE TITLE
New issue with praw

### ISSUE THREAD

**Issue by adikami5665** [voussoir/timesearch#17]
I recently upgraded praw and now I am getting error 
prawcore:Retrying due to ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))) status: GET https://oauth.reddit.com/api/info/

**Comment by voussoir** [comment]
Hi, that sounds like a temporary network error. Is it still happening? This is not caused by timesearch.

**Comment by adikami5665** [comment]
I see thankyou sir
