### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by mnichko** [voussoir/timesearch#5]
Hello, I found your script very useful.

However, the lack of license legally prevents everyone from using and contributing to it (https://choosealicense.com/no-permission/). Could you please provide a license to the repository?

**Comment by voussoir** [comment]
Hi, thanks for making this PR. Good idea. I'm happy with the BSD-3 license and have applied it here: https://github.com/voussoir/timesearch/commit/6fc6c2238d70f4239b877f10e79febc7a0009a48
